/**
 * Shared types for the desktop app's preload↔renderer bridge and update events.
 *
 * The preload exposes a frozen surface via contextBridge; this module is the
 * single source of truth for that surface. The renderer imports its types
 * from a `.d.ts` re-export at `src/renderer-types.d.ts` (auto-generated by
 * tsdown via the preload bundle's `*.d.ts`).
 */

/**
 * URL-detection regex for the child's "ready" line.
 *
 * Matches `dsh web: http://127.0.0.1:<port>` with an optional `(LAN: ...)`
 * suffix. The anchor is `@deepseek-ai/dsh-web-app`'s boot announcement at
 * `packages/bundle/web-app/src/index.ts:265` in upstream `deepseek-harness`.
 */
export const URL_DETECT_RE = /dsh web: (https?:\/\/127\.0\.0\.1:\d+)/

/**
 * A successful URL-detection match: the captured loopback URL.
 */
export interface DetectedUrl {
  readonly url: string
  readonly port: number
}

/**
 * Match the URL line against an arbitrary stdout chunk.
 *
 * Returns the first match or `null` if the chunk does not contain a URL line.
 * Buffer-and-regex in `src/main.ts#UrlDetector` calls this on each accumulated
 * line; exposing it as a pure function keeps it testable in isolation.
 */
export function detectUrl(line: string): DetectedUrl | null {
  const match = URL_DETECT_RE.exec(line)
  if (match === null || match[1] === undefined) return null
  const url = match[1]
  const portMatch = /:(\d+)$/.exec(url)
  if (portMatch === null || portMatch[1] === undefined) return null
  const port = Number.parseInt(portMatch[1], 10)
  if (!Number.isFinite(port)) return null
  return { url, port }
}

/** Surface exposed on `window.dshDesktop` by the preload script. */
export interface DshDesktopApi {
  /** Open `url` in the user's default browser. */
  openExternal(url: string): Promise<void>
  /** The current platform: `'darwin' | 'linux' | 'win32' | ...`. */
  readonly platform: NodeJS.Platform
  /** Subscribe to auto-update progress events. Returns a disposer. */
  onUpdateProgress(listener: (event: UpdateEvent) => void): () => void
  /** Manually trigger an update check. */
  checkForUpdates(): Promise<void>
  /** Quit and apply a downloaded update. */
  quitAndInstall(): Promise<void>
}

/** Auto-update progress event payload. */
export type UpdateEvent =
  | { readonly state: 'checking' }
  | { readonly state: 'available'; readonly version: string }
  | { readonly state: 'not-available' }
  | { readonly state: 'downloading'; readonly percent: number }
  | { readonly state: 'downloaded'; readonly version: string }
  | { readonly state: 'error'; readonly message: string }

/** Channel name constants used by the preload's `ipcRenderer.invoke`. */
export const IPC = {
  openExternal: 'dsh:open-external',
  updateProgress: 'dsh:update-progress',
  checkForUpdates: 'dsh:check-for-updates',
  quitAndInstall: 'dsh:quit-and-install',
} as const